"""add name constraint in storage_items

Revision ID: abaae322e177
Revises: d0ec750d1d44
Create Date: 2026-03-25 00:15:36.952688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abaae322e177"
down_revision: Union[str, Sequence[str], None] = "d0ec750d1d44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name="check_name_is_valid",
        table_name="storage_items",
        condition="name ~ '^[a-zA-Zа-яА-ЯёЁ0-9_. ()-]+$'"
    )
    op.create_check_constraint(
        constraint_name="check_name_stripped_whitespace",
        table_name="storage_items",
        condition="name = TRIM(name)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name="check_name_stripped_whitespace",
        table_name="storage_items",
        type_="check"
    )
    op.drop_constraint(
        constraint_name="check_name_is_valid",
        table_name="storage_items",
        type_="check"
    )
    # ### end Alembic commands ###
