"""add storage_items table

Revision ID: 2e2f41b5d3d1
Revises: 5fff5024963d
Create Date: 2026-02-19 20:32:34.192970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e2f41b5d3d1"
down_revision: Union[str, Sequence[str], None] = "5fff5024963d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("s3_key", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "kind != 'file' OR s3_key IS NOT NULL",
            name="check_s3_key_not_null_for_file",
        ),
        sa.CheckConstraint(
            "kind != 'file' OR size IS NOT NULL", name="check_size_not_null_for_file"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["storage_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name",
            "owner_id",
            "parent_id",
            name="unique_name_within_parent",
            postgresql_nulls_not_distinct=True,
        ),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(
        op.f("ix_storage_items_parent_id"), "storage_items", ["parent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_items_parent_id"), table_name="storage_items")
    op.drop_table("storage_items")
    # ### end Alembic commands ###
